language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '8'
script:
  - cd ReaGQL && yarn install && yarn build
  - cd ReaRest && yarn install && yarn build
  - yarn install && yarn build