language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
notifications:
  email: false

jobs:
  include:
    - stage: ReaGQL
      script: cd ReaGQL && yarn install && yarn build
    - stage: ReaRest
      script: cd ReaRest && yarn install && yarn build
    - stage: rooter
      script: yarn install
    - stage: deploy
      script: skip
      deploy:
        provider: heroku
        app: wearea
        api_key: $HEROKU_API_KEY
        skip_cleanup: true


#script:
#  - cd ReaGQL && yarn install && yarn build
#  - cd ReaRest && yarn install && yarn build
#  - yarn install && yarn build